"""Adicionei Pedido

Revision ID: 09ea14375664
Revises: 01be3ae4c8e5
Create Date: 2021-05-20 20:51:03.344956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ea14375664'
down_revision = '01be3ae4c8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrega_ou_retirada', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('local_de_entrega', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('produto_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_pedido_usuario', type_='foreignkey')
        batch_op.drop_constraint('fk_pedido_produto', type_='foreignkey')
        batch_op.create_foreign_key('fk_pedido_produto', 'produto', ['produto_id'], ['id'])
        batch_op.create_foreign_key('fk_pedido_usuario', 'usuario', ['usuario_id'], ['id'])
        batch_op.drop_column('id_produto')
        batch_op.drop_column('id_usuario')
        batch_op.drop_column('opcao')
        batch_op.drop_column('local_entrega')

    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_usuario', type_='foreignkey')
        batch_op.create_foreign_key('fk_usuario', 'usuario', ['usuario_id'], ['id'])
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_usuario', type_='foreignkey')
        batch_op.create_foreign_key('fk_usuario', 'usuario', ['id_usuario'], ['id'])
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_entrega', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('opcao', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('id_usuario', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('id_produto', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_pedido_usuario', type_='foreignkey')
        batch_op.drop_constraint('fk_pedido_produto', type_='foreignkey')
        batch_op.create_foreign_key('fk_pedido_produto', 'produto', ['id_produto'], ['id'])
        batch_op.create_foreign_key('fk_pedido_usuario', 'usuario', ['id_usuario'], ['id'])
        batch_op.drop_column('produto_id')
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('local_de_entrega')
        batch_op.drop_column('entrega_ou_retirada')

    # ### end Alembic commands ###
